### ISSUE TITLE
Shared App Windows (not entire desktop) disconnects after about 10 minutes

### ISSUE THREAD

**Issue by justinkelly** [pavlobu/deskreen#19] opened 2021-01-19 09:22 UTC
Host: Win 10
Sharing 1 specific app window to another desktop on the local network

Issue: After about 10 minutes the app window on the client disconnects
- if I go to the Connected Devices page on the host, there are no longer any connected devices

Note: When sharing the entire desktop (same host/client) no disconnect occurs

Thanks again!!

Justin

**Comment by pavlobu** [comment] 2021-01-19 10:04
Thank you for using Deskreen!

Very big thanks for submitting this issue. The reason these bugs slipped to first release
is because I mostly developed on my Mac. In future releases I'll make sure we tackle this bug.

Cheers,
Paul

**Comment by musm** [comment] 2021-01-20 00:16
I'm also running into this.

**Comment by musm** [comment] 2021-01-20 00:16
In general the desktop app is extremely slow to interact with and quite "buggy" to respond or reset with user interaction.

**Comment by justinkelly** [comment] 2021-01-20 01:15
note: tested sharing an app window today and lasted about 3 hours before disconnecting 
- not sure if host or client when to sleep or similar and that lost/dropped the connection
- if there is anyway to auto reconnect or similar would  be great thanks

**Comment by pavlobu** [comment] 2021-01-20 08:49
@musm deskreen is an electron app and it requires a lot of resources, on my beefy windows10 machine it flies like butterfly. I cant guarantee that you will have same experience on not powerful enough machines.

@justinkelly  the issues you report are well known problems of current application. It is a new feature that should be implemented, that saves connected machine as trusted and when machine reconnects it starts same sharing session.

the problem with androids and ipads is that when you lock them, after about 30 seconds they go to low power mode and close socket connections

so we need to implement a new feature for this in order to provide better user experience

cheers
Paul

**Comment by pavlobu** [comment] 2021-02-04 19:53
closing due to missing feature. it's not a bug

**Closed by pavlobu** 2021-02-04 19:53 UTC
Labels: bug
